# Generated by Django 4.2 on 2024-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='planned_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
