# Generated by Django 4.2 on 2024-11-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_planned_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='planned_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
