# Generated by Django 4.2 on 2025-03-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_managers'),
        ('accounts', '0005_alter_customuser_first_name'),
    ]

    operations = [
    ]
