# Generated by Django 4.2 on 2024-12-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='outcome.expense'),
        ),
    ]
