# Generated by Django 4.2 on 2024-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0002_alter_outcome_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='expense',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
