# Generated by Django 4.2 on 2024-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0003_alter_outcome_expense_delete_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='amount',
            field=models.DecimalField(decimal_places=False, max_digits=10),
        ),
    ]
